### ISSUE TITLE
Create a dummy database to test the explorer

### ISSUE THREAD

**Issue by StefanoSetti** [affidaty-blockchain/trinci-db-explorer#2]
The project should have a **dummy database**, generated by interactions between various nodes. This is to make it possible to use the explorer and test its functionality.

**Comment by avitsiuk** [comment]
[This](https://mega.nz/file/i0oD2KIA#GL4UEFp0PavsARF60x-ZSgwtswVoVgq75yZpdzj2MMI) is a simple dummy trinci database with some transactions (full content of the database directory).
